services:
  - type: web
    name: flamboyant-api
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: free
    region: ohio
    envVars:
      - key: PORT
        value: 8080
      - key: ALLOWED_ORIGINS
        value: "" # Ex: https://flamboyant-frontend.vercel.app
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION_HOURS
        value: 24
      - key: GEMINI_API_KEY
        sync: false
